name: Naukri Update

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Naukri update script
        run: python ./naukri_update.py
        env:
          NAUKRI_EMAIL_1: ${{ secrets.NAUKRI_EMAIL_1 }}
          NAUKRI_PASSWORD_1: ${{ secrets.NAUKRI_PASSWORD_1 }}
