name: Naukri Resume Update

on:
  workflow_dispatch:        # Manual trigger
  schedule:
    - cron: "30 0 * * *"    # Runs daily at 6:00 AM IST

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # ✅ update to v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Naukri Update Script
        env:
          NAUKRI_EMAIL_1: ${{ secrets.NAUKRI_EMAIL_1 }}
          NAUKRI_PASSWORD_1: ${{ secrets.NAUKRI_PASSWORD_1 }}
        run: python naukri_update.py

      # ✅ Upload logs/screenshots
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
