name: Naukri Resume Update

on:
  schedule:
    - cron: "30 0 * * *"   # Runs daily at 6:00 AM IST
  workflow_dispatch:        # Allows manual trigger

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies (Selenium + WebDriver Manager)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Step 4: Set up headless Chrome (required for Selenium)
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # Step 5: Run the Naukri update script
      - name: Run Naukri Update Script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          python naukri_update.py
